plugins {
    id "java"
    id "xyz.jpenilla.run-paper" version "3.0.2"
    id "io.papermc.paperweight.userdev" version "2.0.0-beta.21"
}

group = "tw.asts.mc"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
    maven {
        name = "papermc-repo"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
    maven {
        name = "sonatype"
        url = "https://oss.sonatype.org/content/groups/public/"
    }
    maven {
        url = "https://repo.opencollab.dev/main/"
    }
    maven {
        url = "https://repo.extendedclip.com/content/repositories/placeholderapi/"
    }
}

dependencies {
    compileOnly "io.papermc.paper:paper-api:26.2.build.+"
    compileOnly "org.geysermc.geyser:api:2.10.0-SNAPSHOT"
    compileOnly "org.geysermc.floodgate:api:2.2.5-SNAPSHOT"
    compileOnly "me.clip:placeholderapi:2.12.2"
    compileOnly files('libs/Residence.jar')
    implementation "net.kyori:adventure-text-minimessage:5.1.1"
    paperweight.paperDevBundle("26.2.build.+")
}

def targetJavaVersion = 25
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"

    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        options.release.set(targetJavaVersion)
    }
}

tasks {
    runServer {
        // Configure the Minecraft version for our task.
        // This is the only required configuration besides applying the plugin.
        // Your plugin's jar (or shadowJar if present) will be used automatically.
        minecraftVersion("26.2")
    }
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset = "UTF-8"
    filesMatching('plugin.yml') {
        expand props
    }
}
